# Common configuration shared between production and development
services:
  sneezy-db:
    container_name: sneezy-db
    volumes:
      - sneezydb:/var/lib/mysql
    restart: always

  sneezy:
    container_name: sneezy
    depends_on:
      - sneezy-db
    cap_add:
      - SYS_PTRACE
    ports:
      - "7900:7900"
    restart: always

  buildertools:
    container_name: sneezy-buildertools
    ports:
      - "5001:5000"
    depends_on:
      - sneezy-db
    restart: always

  websockify:
    container_name: sneezy-websockify
    image: efrecon/websockify
    command:
      - "7901"
      - "sneezy:7900"
    ports:
      - "7901:7901"
    depends_on:
      - sneezy
    restart: always

  webclient:
    container_name: sneezy-webclient
    ports:
      - "8080:80"
    depends_on:
      - websockify
    restart: always

volumes:
  sneezydb:
  sneezy-mutable:
